apiVersion: v1
kind: Service
metadata:
  labels:
    app: iotbox
  name: iotbox
  namespace: pos
spec:
  ports:
  - name: "8070"
    port: 8070
    targetPort: 8069
  - name: "8072"
    port: 8072
    targetPort: 8072
  selector:
    app: iotbox
